import { Inter } from 'next/font/google';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin'],
  weights: [200, 400, 700],
})

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
